# Generated by Django 3.1.7 on 2021-07-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
