# Generated by Django 3.1.7 on 2021-07-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0002_remove_cartitem_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
